ZheNar/ZheNar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'ZheNar.views.index',name = 'index'),
	url(r'^hot/$','ZheNar.views.hot', name = 'hot'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^profiles/', include('profiles.urls', namespace="profiles")),
	url(r'^events/', include('events.urls',namespace="events")),
	url(r'^places/', include('places.urls',namespace="places")),
	
	# url(r'^api/', include('api.urls',namespace="api")),
    # Examples:
    # url(r'^$', 'ZheNar.views.home', name='home'),
    # url(r'^ZheNar/', include('ZheNar.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ZheNar/api/urls.py
from django.conf.urls import patterns, url

from api import views

urlpatterns = patterns('',
	url(r'^$',				views.index, name='index'),
	url(r'^place/$',		views.place, name='place'),
	url(r'^place/type/$',	views.place_type,name='place_type'),
	url(r'^place/create/$', views.place_create,name = 'place_create'),
	url(r'^event/$',		views.event, name='event'),
	url(r'^event/type/$',	views.event_type ,name='event_type'),
	url(r'^event/create/$', views.event_create, name='event_create'),
	url(r'^user/$',			views.user, name='user'),
	url(r'^user/reg/$',		views.user_reg, name='user_reg'),
	url(r'^user/login/username/$',	views.user_login_username, name='user_login_username'),
	url(r'^user/login/email/$',	views.user_login_email, name='user_login_email'),
	url(r'^user/edit/$',		views.user_edit, name='user_edit'),
	url(r'^user/logout/$',		views.user_logout, name='user_logout'),
	url(r'^user/deactive/$',	views.user_deactive, name='user_deactive'),
)

ZheNar/events/urls.py
from django.conf.urls import patterns, url

from events import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^create/$',views.create,name='create'),
	url(r'^_create/$',views._create,name='_create'),
	url(r'^type_create/$',views.type_create,name='type_create'),
	url(r'^_type_create/$',views._type_create,name='_type_create'),
	url(r'^detail/(?P<event_id>\d+)/$',views.detail,name='detail'),
	url(r'^_follow/$',views._follow,name='_follow'),
	url(r'^_unfollow/$',views._unfollow,name='_unfollow'),
	url(r'^insert/$',views.insert,name="insert"), #insert the icon
	url(r'^_delete/(?P<e_id>\d+)/$', views._delete,name='_delete'),
	url(r'^edit/(?P<event_id>\d+)/$',views.edit,name='edit'),
	url(r'^_edit/(?P<event_id>\d+)/$',views._edit,name='_edit'),
)

ZheNar/profiles/urls.py
from django.conf.urls import patterns, url

from profiles import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^debug/(?P<info>[\S ]+)/$', views.debug, name='debug'),
	url(r'^_login/$', views._login, name='_login'),
	url(r'^_logout/$', views._logout, name='_logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^_register/$', views._register, name='_register'),
	url(r'^settings/$', views.settings, name='settings'),
	url(r'^_settings/$', views._settings, name='_settings'),
	url(r'^manage/$', views.manage, name='manage'),
	url(r'^syncSuperUser/$', views.syncSuperUser, name='syncSuperUser'),#for sync the superuser into profile
)

ZheNar/templates/include/error_popup.html
<div class="container">
	<div class="alert alert-block alert-error fade in">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<h4 class="alert-heading">Oh snap! You got an error!</h4>
		<ul>
			{% for error in error_list %}
				<li>{{error}}</li>
			{% endfor %}
		</ul>
	</div>
</div>

ZheNar/templates/include/login_modal.html
	<div id="LogModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<form class="form-signin" action="{% url 'profiles:_login'  %}" method="post">
		{% csrf_token %}
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
					<h2>登录</h2>
			</div>
			<div class="modal-body">
				<input class="input-block-level" name="account" type="text" placeholder="用户名 or 邮箱地址">
				<input class="input-block-level" name="password" type="password" placeholder="密码">
				<label class="checkbox pull-left">
					<input type="checkbox" value="remember-me">
					Remember me
				</label>
				<a href="#" class="pull-right"><p>忘记密码？</p></a>
			</div>
			<div class="modal-footer">
				<button class="btn btn-large btn-primary" type="submit">登录</button>
			</div>
		</form>
	</div>
	

ZheNar/templates/include/nav_authenticated.html
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="{% url 'index'%}">浙哪儿</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="{% url 'hot' %}" >热点</a></li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">事件</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li><a href="{% url 'events:index' %}" >事件列表</a></li>
							<li><a href="{% url 'events:create' %}" >创建事件</a></li>
							<li><a href="{% url 'events:type_create' %}" >创建事件类型</a></li>
						</ul>
					</li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#">地点</a>
						<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
							<li><a href="{% url 'places:index' %}" >地点列表</a></li>
							<li><a href="{% url 'places:create' %}" >创建地点</a></li>
							<li><a href="{% url 'places:type_create' %}" >创建地点类型</a></li>
						</ul>
					</li>
				</ul>
				<ul class="nav pull-right">
					<div class="btn-group">
						<a class="btn" href="{% url 'profiles:manage' %}"><i class="icon-large icon-user"></i>{{ username }}</a>
						<a class="btn dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'profiles:manage' %}"><i class="icon-large icon-cog "></i>管理</a></li>
							<li><a href="{% url 'profiles:settings' %}"><i class="icon-large icon-edit "></i>设置</a></li>
							<li><a href="{% url 'profiles:_logout' %}"><i class="icon-large icon-eject "></i>登出</a></li>
						</ul>
					</div>
				</ul>
			</div>
		</div>
	</div>
</div>

ZheNar/templates/include/nav_unauthenticated.html
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="{% url 'index'%}">浙哪儿</a>
			<div class="nav-collapse collapse">
				<ul class="nav">
					<li><a href="#">帮助</a></li>
					<li><a href="#">How it Works</a></li>
				</ul>
				<ul class="nav pull-right">
					<li><a href="#LogModal" data-toggle="modal">登录</a></li>

					<li><a href="{% url 'profiles:register'  %}" data-toggle="modal">注册</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>

ZheNar/templates/include/register_modal.html
	<div id="LogModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<form class="form-signin" action="{% url 'profiles:_login'  %}" method="post">
		{% csrf_token %}
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
					<h2>登录</h2>
			</div>
			<div class="modal-body">
				<input class="input-block-level" name="account" type="text" placeholder="用户名 or 邮箱地址">
				<input class="input-block-level" name="password" type="password" placeholder="密码">
				<label class="checkbox">
					<input type="checkbox" value="remember-me">
					Remember me
				</label>
			</div>
			<div class="modal-footer">
				<button class="btn btn-large btn-primary" type="submit">登录</button>
			</div>
		</form>
	</div>
	
	<div id="infoModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		{% csrf_token %}
		<div class="modal-header">
			<h2>提醒</h2>
		</div>
		<div class="modal-body">
			<p>你还没有登录呢！</p>
		</div>
		<div class="modal-footer">
			<button class="btn" data-dismiss="modal" aria-hidden="true">确定</button>
		</div>
	</div>