ZheNar/ZheNar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'ZheNar.views.index',name = 'index'),
	url(r'^hot/$','ZheNar.views.hot', name = 'hot'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^profiles/', include('profiles.urls', namespace="profiles")),
	url(r'^events/', include('events.urls',namespace="events")),
	url(r'^places/', include('places.urls',namespace="places")),
	
	# url(r'^api/', include('api.urls',namespace="api")),
    # Examples:
    # url(r'^$', 'ZheNar.views.home', name='home'),
    # url(r'^ZheNar/', include('ZheNar.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ZheNar/api/urls.py
from django.conf.urls import patterns, url

from api import views

urlpatterns = patterns('',
	url(r'^$',				views.index, name='index'),
	url(r'^place/$',		views.place, name='place'),
	url(r'^place/type/$',	views.place_type,name='place_type'),
	url(r'^place/create/$', views.place_create,name = 'place_create'),
	url(r'^event/$',		views.event, name='event'),
	url(r'^event/type/$',	views.event_type ,name='event_type'),
	url(r'^event/create/$', views.event_create, name='event_create'),
	url(r'^user/$',			views.user, name='user'),
	url(r'^user/reg/$',		views.user_reg, name='user_reg'),
	url(r'^user/login/username/$',	views.user_login_username, name='user_login_username'),
	url(r'^user/login/email/$',	views.user_login_email, name='user_login_email'),
	url(r'^user/edit/$',		views.user_edit, name='user_edit'),
	url(r'^user/logout/$',		views.user_logout, name='user_logout'),
	url(r'^user/deactive/$',	views.user_deactive, name='user_deactive'),
)

ZheNar/places/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from places import views

urlpatterns = patterns('',
	url(r'^$',views.index, name='index'),
	url(r'^_debug/$',views.debug, name='debug'),
	url(r'^create/$', views.create,name='create'),
	url(r'^_create/$', views._create,name='_create'),
	url(r'^detail/(?P<place_id>\d+)/$',views.detail,name='detail'),
	url(r'^edit/(?P<place_id>\d+)/$',views.edit,name='edit'),
	url(r'^_edit/$',views._edit,name='_edit'),
	url(r'^type_create/$', views.type_create,name='type_create'),
	url(r'^_type_create/$', views._type_create,name='_type_create'),
	url(r'^insert/$',views.insert,name="insert"), #用于插入icon
	#url(r'^modify$',views.create,name='modify'),
	#url(r'^_delete/(?P<place_id>\d+)/$', views._delete,name='_delete'),

)

ZheNar/places/models.py
from django.db import models
from profiles.models import Profile
from django.contrib.auth.models import User
from django.db.models import Count

#from events.models import Event
# Create your models here.
class Icon(models.Model):
	name = models.CharField(unique=True,max_length=255)
	
	def __unicode__(self):
		return self.name[:-4]
	
class PlaceType(models.Model):
	STATUS_SET = (
	(1,"Pending"),
	(2,"Accepted"),
	(3,"Rejected"),
	(4,"Deleted"),
	)
	status = models.SmallIntegerField(default = 1,choices = STATUS_SET)
	name = models.CharField(unique=True, max_length = 255,blank=False)
	icon = models.ForeignKey(Icon)
	#color: (optional) specifies a color either as a 24-bit (example: color=0xFFFFCC) 
	#or 32-bit hexadecimal value (example: color=0xFFFFCCFF), 
	#or from the set {black, brown, green, purple, yellow, blue, gray, orange, red, white}.


	def __unicode__(self):
		return self.name

class Place(models.Model):
	CHOICE_SET = (
	(1,"Pending"),
	(2,"Accepted"),
	(3,"Rejected"),
	(4,"Deleted"),
	)
	ZOOM_SET = (
	(16,"Large Level"),
	(17,"Middle Level"),
	(18,"Bottom Level"),
	)

	status = models.SmallIntegerField(default = 1,choices = CHOICE_SET)
	name = models.CharField(max_length = 255)
	creater = models.ForeignKey(User)
	description = models.TextField(blank = True)
	place_type = models.ForeignKey(PlaceType)
	latitude = models.FloatField()
	longitude = models.FloatField()
	create_time = models.DateField()
	zoom_level = models.SmallIntegerField(default = 18,choices = ZOOM_SET)
	events_followers = models.BigIntegerField(default = 0)
	
	def __unicode__(self):
		return self.name

	def showStatus(self):
		if self.status == 1: return "Pending"
		if self.status == 2: return "Accepted"
		if self.status == 3: return "Rejected"

	def syncEventsFollowers(self):
		self.events_followers = 0
		events = self.place_events_set.filter(status=2)
		for item in events:
			if not item.if_event_was_expired():
				self.events_followers += item.follower.count()
		#self.save()
	
	def __lt__(self, other):
		return self.events_followers >= other.events_followers


	class Meta:
		ordering = ['name']
		permissions = (
			('create_map_place', 'Can create map place'),
			('modify_map_place', 'Can modify map place'),
			('remove_map_place', 'Can remove map place'),
		)

ZheNar/places/views.py
# -*- coding: utf-8 -*-
from django.template import Template, Context, loader, RequestContext
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response, render
from django.contrib.auth.models import User
from datetime import datetime
from places.models import PlaceType,Place,Icon
from profiles.models import Profile
from events.models import Event

def login_proc(request):
	if request.user.is_authenticated():
		return {
			"authenticated":True, 
			"username":request.user,
			}
	else:
		return {}
	
def debug(request, info):
	return HttpResponse("debug information: " + info)

def index(request):
	if request.user.is_authenticated():
		place_list = Place.objects.all()
			
		c = Context({"page_title": "ZJU地点",
					 "places": place_list,
					 })
		return render_to_response('places/place_index.html',c,context_instance = RequestContext(request,processors=[login_proc]))
	else:
		return HttpResponseRedirect(reverse('index'))
	
	
def create(request):
	if request.user.is_authenticated():
		m_place_type = PlaceType.objects.all()
		c = Context({
		"page_title": "ZJU地点",
		"place_options":m_place_type,
					})
		return render_to_response('places/place_create.html',c,context_instance = RequestContext(request,processors=[login_proc]))
	else:
		return HttpResponseRedirect(reverse('index'))
	
def _create(request):
	if request.POST:
		m_place_name = request.POST.get('place_name')
		m_place_type_name = request.POST.get('place_type')
		m_latitude = request.POST.get('latitude')
		m_longitude = request.POST.get('longitude') 
		m_description = request.POST.get('description')
		m_creater_id = request.user.id
	else:
		return HttpResponseRedirect(reverse('index'))
		
	try:
		place = Place.objects.get(name = m_place_name,latitude = m_latitude, longitude = m_longitude,description = m_description)
	except Place.DoesNotExist:
		try:
			m_creater = User.objects.get(pk=m_creater_id)
		except User.DoesNotExist:
			return HttpResponseRedirect(reverse('index'))

		m_place_type = PlaceType.objects.get(name = m_place_type_name)
		place = Place(creater = m_creater, name = m_place_name,description = m_description, place_type = m_place_type,latitude = m_latitude, longitude = m_longitude,create_time = datetime.now())
		if request.user.is_superuser: 
			place.status = 2
		place.save()
		return HttpResponseRedirect(reverse('places:index'))
	
	return HttpResponseRedirect(reverse('index'))

def detail(request,place_id):
	try:
		m_place = Place.objects.get(pk = place_id)
	except Place.DoesNotExist:
		return __goErrorPage(request, ['There is no such place', ])
	m_events = Event.objects.filter(place = m_place)

	c = Context({"page_title": "浙Nar儿的地点详情",
	"place": m_place,
	"events_in_place": m_events,
	})
	return render_to_response('places/place_detail.html',c,context_instance = RequestContext(request,processors=[login_proc]))
	
	
def type_create(request):
	if request.user.is_authenticated():
		type_icon_list = Icon.objects.all()
		c = Context({
				"page_title": "ZJU地点-创建地点类型",
				"icon_list":type_icon_list,
		})
		return render_to_response('places/place_type_create.html',c,context_instance = RequestContext(request,processors=[login_proc]))
	else:
		return HttpResponseRedirect(reverse('places:index'))
	
def _type_create(request):
	error_list = []
	if request.POST:
		m_type_name = request.POST.get("place_type")
		m_type_icon = request.POST.get("place_icon")
	else:
		return HttpResponseRedirect(reverse('places:index'))
		
	try:
		m_place_type = PlaceType.objects.get(name = m_type_name,status = 2)
	except PlaceType.DoesNotExist:
		m_icon = Icon.objects.get(name = m_type_icon)
		m_place_type = PlaceType(name = m_type_name, icon = m_icon)
		if request.user.is_superuser: 
			m_place_type.status = 2
		m_place_type.save()
		return HttpResponseRedirect(reverse('places:index'))
	
	return HttpResponseRedirect(reverse('index'))


def _delete(request, place_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('index'))
	place = Place.objects.get(pk = place_id)
	if place.creater_id == request.user.id:
		place.status = 4
		place.save()
	return HttpResponseRedirect(reverse('profiles:manage'))
	
def edit(request,place_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('index'))

	m_place = Place.objects.get(pk = place_id)
	m_place_type = PlaceType.objects.all()
	
	if m_place.creater.id != request.user.id:
		return __goErrorPage(request,["Oops, this place is not created by you, you can't modify it"])
		
	c = Context({
		"title":"ZheNar修改地点",
		"place_options":m_place_type,
		"place": m_place,
	})
	
	return render_to_response('places/place_edit.html',c,context_instance = RequestContext(request,processors=[login_proc]))
	
def _edit(request):
	if request.POST:
		m_place_id = request.POST.get('place_id')
		m_place_name = request.POST.get('place_name')
		m_place_type_name = request.POST.get('place_type')
		m_latitude = request.POST.get('latitude')
		m_longitude = request.POST.get('longitude') 
		m_description = request.POST.get('description')
		m_creater_id = request.user.id
	else:
		return HttpResponseRedirect(reverse('index'))
		
	try:
		m_place = Place.objects.get(pk = m_place_id)
	except Place.DoesNotExist:
		return HttpResponseRedirect(reverse('index'))
	
	if m_place.creater.id != request.user.id:
		return __goErrorPage(request,["Oops, this place is not created by you, you can't modify it"])
	
	try:
		m_creater = User.objects.get(pk=m_creater_id)
	except User.DoesNotExist:
		return HttpResponseRedirect(reverse('index'))

	m_place_type = PlaceType.objects.get(name = m_place_type_name)
	m_place.creater = m_creater
	m_place.name = m_place_name
	m_place.description = m_description
	m_place.place_type = m_place_type
	m_place.latitude = m_latitude
	m_place.longitude = m_longitude
	m_place.create_time = datetime.now()
	m_place.status = 1
	if request.user.is_superuser: 
		m_place.status = 2
	m_place.save()
	return HttpResponseRedirect(reverse('places:index'))
	
def __goErrorPage(request, error_list):
	return render(request, "error/error_popup.html", __login_proc(request, {'error_list': error_list}))
	
#用于插入icon用，已插入则无需再用
def insert(request):
	list = []
	f = open('static/map_icon/icons/icon_list.txt','r')
	for line in f:
		list += line.splitlines()
	for item in list:
		icon = Icon(name= item)
		icon.save()
	return HttpResponseRedirect(reverse('places:index'))


ZheNar/templates/places/place_create.html
{% extends "base.html" %}
{% block css %}
<style>
 	#map_canvas{
		padding:10px;
		border:1px solid;
		margin: 0 auto;
		border-radius:5px;
		box-shadow: 2px 2px 2px #888888;
		height:400px;	
	}
	#google_map{
		height:400px;
	}
</style>
{% endblock %}
{% block script %}
<script src='http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false'>
</script>
<script>
	var map;
	var myCenter=new google.maps.LatLng(30.3045022222222,120.08633333333);
	var marker;
	var infowin;

	function initialize()
	{
		var opt = { minZoom: 16, maxZoom: 18 };
		var mapConfig = {
			center:myCenter,
			zoom:18,
			mapTypeId:google.maps.MapTypeId.ROADMAP,
		};
		map = new google.maps.Map(document.getElementById('google_map'),mapConfig);
		map.setOptions(opt);

		google.maps.event.addListener(map, 'click', function(event) {
			placeMarker(event.latLng);
		});
	}

	function placeMarker(location) {
		var icon_base = "http://google-maps-icons.googlecode.com/files/";
		if(marker){
			marker.setMap(null);
		}
		var icon_name = $("#type_option :selected").val();
		var my_icon = $("#"+icon_name).val();
		marker = new google.maps.Marker({
			position: location,
			map: map,
			icon: icon_base + my_icon + ".png",
			title: $("#pname").val()
		});

		document.getElementById('lng').value = location.lng();
		document.getElementById('lat').value = location.lat();
	}

	google.maps.event.addDomListener(window, 'load', initialize);
</script>
<script>
	function check_form(){
		var lng = $("#lng").val()
		var lat = $("#lat").val();
		var place_name = $("#pname").val();
		var place_type = $("#type_option :selected").val();
		var desc = $("#desc").val();
		if(lng && lat && place_name && place_type && desc)
		{
			if(place_name.length >= 8)
				$("#alert_form").text("地点名称不能超过7个字符，请不要在地点名中包含‘浙江大学’等冗余字样");
			else if(desc.length >= 255)
				$("#alert_form").text("地点描述不能超过255个字符");
			else
				return true;
		}
		else{
			$("#alert_form").text("请确保表单填写完毕，并且已在地图上设置过位置标记，再次提交");	
		}
		$(".alert").removeClass("out");
		$(".alert").addClass("in");
		return false;
	}
	function close_alert(){
		$(".alert").removeClass("in");
		$(".alert").addClass("out");
	}
</script>
{% endblock %}
{% block main %}
<div class="container" style="padding:40px">
	<div class="alert alert-block alert-error fade out" data-alert="alert">
		<button class="close" type="button" onclick="close_alert();">×</button>
		<strong>错误</strong>
		<div id="alert_form">
			
		</div>
	</div>
	<div class="container-fluid">
		<form action="{% url 'places:_create'  %}" method='post' onsubmit='return check_form();'>
		{% csrf_token %}
			<h2>创建地点</h2>
			<div class="row-fluid">
				<fieldset class="span8">
					<legend>地理信息:</legend>
					<div id="map_canvas"  >
						<div id="google_map" class="spa7"></div>
					</div>
					<input id='lng' name="longitude" type="hidden" value=''>
					<input id='lat' name="latitude" type="hidden" value=''>
				</fieldset>
				<fieldset class="span4">
					<legend>具体信息:</legend>
					<input id="pname" type="text" name="place_name" class="input-block-level" placeholder="地点名称" />
					<select id="type_option" name="place_type">
						{% for option in place_options %}
							{% if option.status == 2 %}
								<option value="{{ option }}">{{ option }}</option>
							{% endif %}
						{% endfor %}
					</select>
					{% for option in place_options %}
						{% if option.status == 2 %}
							<input id='{{option}}' type="hidden" value='{{option.icon}}'>
						{% endif %}
					{% endfor %}
					<textarea id="desc" name="description" class="input-block-level" placeholder="具体描述信息" rows="14" cols="40"></textarea> 
				</fieldset>
				<button class="btn btn-large btn-primary span2" type="submit">创建</button>
				<button class="btn btn-large btn-primary span2" onclick="location.href='{% url 'places:index' %}'">取消</button>
		  
		</form>
	</div>
</div>
{% endblock %}

ZheNar/templates/places/place_detail.html
{% extends "base.html" %}
{% block css %}
<style type="text/css" media="screen">
	.description{
		position: relative;
		margin: 0px 0px 20px 0px;
		padding: 10px 20px 10px 20px;
		background-color: #fff;
		border: 1px solid #ddd;
		-webkit-border-radius: 4px;
		-moz-border-radius: 4px;
		border-radius: 4px;
		height:180px;
		overflow:scroll;
	}
	#event-list{
		height:440px;
		overflow: scroll;
	}
</style>
{% endblock %}
{% block script %}
{% endblock %}
{% block main %}
<div class="container" style="margin-top:40px;">
	<div class="row-fluid" style="margin-top:40px;">
		<div class="span4">
			<div class="thumbnail">
				<img src="http://maps.googleapis.com/maps/api/staticmap?center={{place.latitude}},{{place.longitude}}&zoom=16&size=300x300&sensor=false&markers=icon:http://google-maps-icons.googlecode.com/files/{{place.place_type.icon.name}}%7Clabel:Z%7C{{place.latitude}},{{place.longitude}}" style="width:348px;max-height:400px;">
				<div class="caption">
					<h3>{{place.name}}</h3>
					<h5>{{place.place_type.name}}</h5>
				</div>
			</div>
		</div>
		<div class="span7" style="margin-left:60px;">
			<div id="event-list" class="row well">
				<table class="table table-hover">
					<caption><h4>事件列表</h4></caption>
					<tr>
						<th>事件名称</th>
						<th>具体地点</th>
						<th>开始时间</th>
						<th>结束时间</th>
						<th>关注度</th>
					</tr>
					{% for event in events_in_place %}
					<tr>
						<td><a href="{% url 'events:detail' event.id %}">{{event.name}}</a></td>
						<td>{{event.address}}</td>
						<td>{{event.start_time}}</td>
						<td>{{event.end_time}}</td>
						<td><span id="counter{{event.id}}" class="label label-info">{{event.follower_count}}</span></td>
					</tr>
					{% endfor %}
				</table>
			</div>
		</div>
		<div class="row" style="width:1100px; margin-left:0px;">
			<div class="description">
				<p>
					<div class="label">地点描述</div>
					{{place.description}}
				</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

ZheNar/templates/places/place_edit.html
{% extends "base.html" %}
{% block css %}
<style>
 	#map_canvas{
		padding:10px;
		border:1px solid;
		margin: 0 auto;
		border-radius:5px;
		box-shadow: 2px 2px 2px #888888;
		height:400px;	
	}
	#google_map{
		height:400px;
	}
</style>
{% endblock %}
{% block script %}
<script src='http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false'>
</script>
<script>
	var map;
	var MyPosition = new google.maps.LatLng({{place.latitude}},{{place.longitude}});
	var marker;
	var infowin;

	function initialize()
	{
		var icon_base = "http://google-maps-icons.googlecode.com/files/";
		var opt = { minZoom: 16, maxZoom: 18 };
		var mapConfig = {
			center:MyPosition,
			zoom:18,
			mapTypeId:google.maps.MapTypeId.ROADMAP,
		};
		map = new google.maps.Map(document.getElementById('google_map'),mapConfig);
		map.setOptions(opt);
		
		my_icon = "{{place.place_type.icon.name}}";
		marker = new google.maps.Marker({
			position:MyPosition,
			map:map,
			icon:icon_base + my_icon,
			title: "My marker"
		});
		google.maps.event.addListener(map, 'click', function(event) {
			placeMarker(event.latLng);
		});
	}

	function placeMarker(location) {
		var icon_base = "http://google-maps-icons.googlecode.com/files/";
		if(marker){
			marker.setMap(null);
		}
		var icon_name = $("#type_option :selected").val();
		var my_icon = $("#"+icon_name).val();
		marker = new google.maps.Marker({
			position: location,
			map: map,
			icon: icon_base + my_icon + ".png",
			title: $("#pname").val()
		});

		document.getElementById('lng').value = location.lng();
		document.getElementById('lat').value = location.lat();
	}

	google.maps.event.addDomListener(window, 'load', initialize);
</script>
<script>
	function check_form(){
		var lng = $("#lng").val()
		var lat = $("#lat").val();
		var place_name = $("#pname").val();
		var place_type = $("#type_option :selected").val();
		var desc = $("#desc").val();
		if(lng && lat && place_name && place_type && desc)
		{
			if(place_name.length >= 8)
				$("#alert_form").text("地点名称不能超过7个字符，请不要在地点名中包含‘浙江大学’等冗余字样");
			else if(desc.length >= 255)
				$("#alert_form").text("地点描述不能超过255个字符");
			else
				return true;
		}
		else{
			$("#alert_form").text("请确保表单填写完毕，并且已在地图上设置过位置标记，再次提交");	
		}
		$(".alert").removeClass("out");
		$(".alert").addClass("in");
		return false;
	}
	function close_alert(){
		$(".alert").removeClass("in");
		$(".alert").addClass("out");
	}
</script>
{% endblock %}
{% block main %}
<div class="container" style="padding:40px">
	<div class="alert alert-block alert-error fade out" data-alert="alert">
		<button class="close" type="button" onclick="close_alert();">×</button>
		<strong>错误</strong>
		<div id="alert_form">

		</div>
	</div>
	<div class="container-fluid">
		<form action="{% url 'places:_edit'  %}" method='post' onsubmit='return check_form();'>
		{% csrf_token %}
			<h2>修改地点信息</h2>
			<div class="row-fluid">
				<fieldset class="span8">
					<legend>地理信息:</legend>
					<div id="map_canvas"  >
						<div id="google_map" class="spa7"></div>
					</div>
					<input id='place_id' name="place_id" type="hidden" value="{{place.id}}">
					<input id='lng' name="longitude" type="hidden" value="{{place.longitude}}">
					<input id='lat' name="latitude" type="hidden" value="{{place.latitude}}">
				</fieldset>
				<fieldset class="span4">
					<legend>具体信息:</legend>
					<input id="pname" type="text" name="place_name" class="input-block-level" placeholder="地点名称" value="{{place.name}}" />
					<select id="type_option" name="place_type" value="{{place.place_type}}">
						{% for option in place_options %}
							{% if option.status == 2 %}
								<option value="{{ option }}">{{ option }}</option>
							{% endif %}
						{% endfor %}
					</select>
					{% for option in place_options %}
						{% if option.status == 2 %}
							<input id='{{option}}' type="hidden" value='{{option.icon}}'>
						{% endif %}
					{% endfor %}
					<textarea id="desc" name="description" class="input-block-level" placeholder="具体描述信息" rows="14" cols="40">{{place.description}}</textarea> 
				</fieldset>
				<button class="btn btn-large btn-primary span2" type="submit">保存</button>
				<button class="btn btn-large btn-primary span2" onclick="location.href='{% url 'places:index' %}'">取消</button>

		</form>
	</div>
</div>
{% endblock %}

ZheNar/templates/places/place_index.html
{% extends "base.html" %}
{% block main %}
<div class="container" style="padding:40px">
	<div class="container-fluid">
		<ul class="thumbnails" style="margin-top:40px;">
		{% for place in places %}
			{% if place.status == 2 %}
				<li class="span3" style="margin:10px">
					<div class="thumbnail">
					   	<a href="{% url 'places:detail' place.id %}">
						   	<img src="http://maps.googleapis.com/maps/api/staticmap?center={{place.latitude}},{{place.longitude}}&zoom=16&size=300x300&sensor=false&markers=icon:http://google-maps-icons.googlecode.com/files/{{place.place_type.icon.name}}%7Clabel:Z%7C{{place.latitude}},{{place.longitude}}">
					   	</a>
						<div class="caption">
							<h4 style="width:240px;overflow:hidden;text-align:left;">{{ place.name}}</h4>
							<h5 style="width:240px;overflow:hidden;text-align:right;">{{place.place_type.name}}</h5>
							<p style="height:100px;width:240px;overflow:scroll;">
							{{place.description}}
							</p>
							<a class="btn btn-info" href="{% url 'places:detail' place.id %}">更多信息</a>
						</div>
					
					</div>
				</li>
			{% endif %}
		{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

ZheNar/templates/places/place_type_create.html
{% extends "base.html" %}
{% block css %}
<style>
	.the-icons{
		margin-left: 0;
		list-style: none;
	}
	.srollspy{
		position: relative;
		margin: 15px 0;
		padding: 39px 19px 14px;
		background-color: #fff;
		border: 1px solid #ddd;
		-webkit-border-radius: 4px;
		-moz-border-radius: 4px;
		border-radius: 4px;
		overflow: scroll;
		height:300px;
	}
</style>
{% endblock %}
{% block script %}
<script>
	function check_form(){
		if($("#ptype").val())
		{
			return true;
		}
		$(".alert").removeClass("out");
		$(".alert").addClass("in");
		return false;
	}
	function close_alert(){
		$(".alert").removeClass("in");
		$(".alert").addClass("out");
	}
</script>
{% endblock %}
{% block main %}
<div class="container" style="padding:40px;">
	<div class="alert alert-block alert-error fade out" data-alert="alert">
		<button class="close" type="button" onclick="close_alert();">×</button>
		<strong>错误</strong>
		请确保表单填写完毕，再次提交
	</div>
	<div class="span12">
		<form action="{% url 'places:_type_create' %}" method="post" onsubmit="return check_form();">
		{% csrf_token %}
			<fieldset class="row span5">
				<h3>创建地点类型</h3>
				<div class="row">
					<div class="span3">
						<input id="ptype" type="text" name="place_type" class="input-block-level" placeholder="地点类型" />
					</div>
				</div>
				<div class="span5" style="margin-left:0px;">
					<select name="place_icon">
						{% for icon in icon_list %}
							<option value="{{ icon.name }}">{{ icon }}</option>
						{% endfor %}
					</select>
				</div>
				<button id="create" class="btn btn-large btn-primary" type="submit">创建</button>
				<button class="btn btn-large btn-primary" onclick="location.href='{% url 'places:index' %}'">取消</button>
				
			</fieldset>
		</form>
		<div class="row span10">
			<div id="heading">
				<h3>地点图标</h3>
			</div>
			<div class="srollspy span10" data-spy="scroll" data-target="#heading" data-offset="0">
				<ul class="the-icons span10">
				{% for icon in icon_list %}
					<li class="span3"><img src="/static/map_icon/icons/{{icon.name}}" style="height:37px;">
					{{icon}}
					</li>
				{% endfor %}
				</ul>
			</div>
		</div>
	</div>
</div>
{% endblock %}