ZheNar/ZheNar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'ZheNar.views.index',name = 'index'),
	url(r'^hot/$','ZheNar.views.hot', name = 'hot'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^profiles/', include('profiles.urls', namespace="profiles")),
	url(r'^events/', include('events.urls',namespace="events")),
	url(r'^places/', include('places.urls',namespace="places")),
	
	# url(r'^api/', include('api.urls',namespace="api")),
    # Examples:
    # url(r'^$', 'ZheNar.views.home', name='home'),
    # url(r'^ZheNar/', include('ZheNar.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ZheNar/api/urls.py
from django.conf.urls import patterns, url

from api import views

urlpatterns = patterns('',
	url(r'^$',				views.index, name='index'),
	url(r'^place/$',		views.place, name='place'),
	url(r'^place/type/$',	views.place_type,name='place_type'),
	url(r'^place/create/$', views.place_create,name = 'place_create'),
	url(r'^event/$',		views.event, name='event'),
	url(r'^event/type/$',	views.event_type ,name='event_type'),
	url(r'^event/create/$', views.event_create, name='event_create'),
	url(r'^user/$',			views.user, name='user'),
	url(r'^user/reg/$',		views.user_reg, name='user_reg'),
	url(r'^user/login/username/$',	views.user_login_username, name='user_login_username'),
	url(r'^user/login/email/$',	views.user_login_email, name='user_login_email'),
	url(r'^user/edit/$',		views.user_edit, name='user_edit'),
	url(r'^user/logout/$',		views.user_logout, name='user_logout'),
	url(r'^user/deactive/$',	views.user_deactive, name='user_deactive'),
)

ZheNar/events/urls.py
from django.conf.urls import patterns, url

from events import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^create/$',views.create,name='create'),
	url(r'^_create/$',views._create,name='_create'),
	url(r'^type_create/$',views.type_create,name='type_create'),
	url(r'^_type_create/$',views._type_create,name='_type_create'),
	url(r'^detail/(?P<event_id>\d+)/$',views.detail,name='detail'),
	url(r'^_follow/$',views._follow,name='_follow'),
	url(r'^_unfollow/$',views._unfollow,name='_unfollow'),
	url(r'^insert/$',views.insert,name="insert"), #insert the icon
	url(r'^_delete/(?P<e_id>\d+)/$', views._delete,name='_delete'),
	url(r'^edit/(?P<event_id>\d+)/$',views.edit,name='edit'),
	url(r'^_edit/(?P<event_id>\d+)/$',views._edit,name='_edit'),
)

ZheNar/profiles/urls.py
from django.conf.urls import patterns, url

from profiles import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^debug/(?P<info>[\S ]+)/$', views.debug, name='debug'),
	url(r'^_login/$', views._login, name='_login'),
	url(r'^_logout/$', views._logout, name='_logout'),
	url(r'^register/$', views.register, name='register'),
	url(r'^_register/$', views._register, name='_register'),
	url(r'^settings/$', views.settings, name='settings'),
	url(r'^_settings/$', views._settings, name='_settings'),
	url(r'^manage/$', views.manage, name='manage'),
	url(r'^syncSuperUser/$', views.syncSuperUser, name='syncSuperUser'),#for sync the superuser into profile
)

ZheNar/profiles/models.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
import datetime


# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(User)
	name = models.CharField(max_length=255, blank=True, null=True)
	GENDER_CHOICES = (
        	(1, _('Male')),
        	(2, _('Female')),
	)
	gender = models.PositiveSmallIntegerField(_('gender'),
                                              choices=GENDER_CHOICES,
                                              blank=True,
                                              null=True)
	registerTime = models.DateTimeField(blank = True, null = True)

	def __unicode__(self):
		return self.user.username
		

ZheNar/profiles/views.py
# Create your views here.
# <-* encoding=utf8 *->
from django.shortcuts import get_object_or_404, render
from django.template import Context, loader
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from datetime import datetime
from django.views.decorators.http import require_POST, require_GET

from profiles.models import Profile
from places.models import Place
from events.models import Event

import re, random


def index(request):
	return HttpResponse("index!")


def debug(request, info):
	return HttpResponse("debug information: " + info)


@require_POST
def _login(request):
	if request.POST:
		account = request.POST['account']
		password = request.POST['password']
	else:
		return HttpResponseRedirect(reverse('index'))

	upr = authenticate(username=account, password=password)
	if upr is None:
		try:
			upr = User.objects.get(email=account)
			upr = authenticate(username=upr.username, password=password) #check if user logins with email
		except User.DoesNotExist:
			return __goErrorPage(request, ["Wrong account or password", ])

	if upr is None:
		return __goErrorPage(request, ["Wrong account or password", ])
	else :
		if upr.is_active == 0:					#This user has not been active
			return __goErrorPage(request, ["This user have been disactivated", ])
		#if upr.is_superuser == 1:				#Superuser should not login in this page
		#	return __goErrorPage(request, ["Superuser should not login in this page", ])
	
	login(request, upr)		#log in
	return HttpResponseRedirect(reverse('index'))


def _logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))


def register(request):
	context = {'page_title': "浙哪儿注册喽！", }
	return render(request, 'profiles/register.html', __login_proc(request, context))


@require_POST
def _register(request):
	if request.POST:
		username = request.POST.get('username')
		email = request.POST.get('email')
		password = request.POST.get('password')
		name = request.POST.get('name')
		gender = 0
		if request.POST.get('gender') == "1":
			gender = 1
		elif request.POST.get('gender') == "2":
			gender = 2
		registerTime = datetime.now()
	else:
		return HttpResponseRedirect(reverse('index'))

	try:
		upr = User.objects.get(username=username)	#check if there is duplicated username
	except User.DoesNotExist:
		upr = None
	if upr is not None:
		return __goErrorPage(request, ["duplicated username", ])

	try:
		upr = User.objects.get(email=email)		#check if there is duplicated email
	except User.DoesNotExist:
		upr = None
	if upr is not None:	
		return __goErrorPage(request, ["dupicated email!", ])
	
	form = {}
	if __judge_form(form):
		upr = User.objects.create_user(username, email, password)
		pr = Profile(user=upr, name=name, gender=gender, registerTime=registerTime)
		pr.save()
		userpr = authenticate(username=username, password=password)
		login(request, userpr)
	else:
		return __goErrorPage(request, ["something wrong with your form", ])
	
	return HttpResponseRedirect(reverse('index'));


def settings(request):
	if request.user.is_authenticated():
		pr = Profile.objects.get(user_id=request.user.id);
		check1 = "";
		check2 = "";
		if pr.gender == 1:
			check1 = "checked"
		if pr.gender == 2:
			check2 = "checked"
		back_info = request.session.get('back_info')
		context = {
			'page_title': '浙哪儿设置',
			'pr': pr,
			'check1': check1,
			'check2': check2,
			'back_info': back_info,
		}
		request.session['back_info'] = None
		
		return render(request, "profiles/settings.html", __login_proc(request, context))
	else :
		return HttpResponseRedirect(reverse('index'))


def _settings(request):
	if request.user.is_authenticated() and request.POST:
		username = request.user.username
		email = request.user.email
		change_password = request.POST.get('change_password')
		if change_password: 
			password = request.POST.get('password')
			ori_password = request.POST.get('password_ori')
		name = request.POST.get('name')
		gender = request.POST.get('gender')
	else:
		return HttpResponseRedirect(reverse('index'))

	form = {}
	if __judge_form(form):
		upr = request.user
		if change_password == "1":
			upr = authenticate(username=username, password=ori_password) #check if ori_password match the user name
			if upr is None:
				return __goErrorPage(request, ["your original password is not right", ])
			upr.set_password(password)
			upr.save()
		pr = Profile.objects.get(user_id = upr.id)
		pr.name = name
		pr.gender = gender
		pr.save()
	else:
		return __goErrorPage(request, ["something wrong with your form", ])

	
	request.session['back_info'] = "保存成功！"
	return HttpResponseRedirect(reverse('profiles:settings'))


def manage(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse("index"))

	place_list_tmp = Place.objects.filter(creater_id = request.user.id)
	place_list = [item for item in place_list_tmp if item.status != 4]
	pr = Profile.objects.get(user_id = request.user.id)
	event_list_tmp = Event.objects.filter(holder_id = pr.id)
	event_list = [item for item in event_list_tmp if item.status != 4]
	
	context = {
			"page_title": "浙哪儿 - 管理你的活动",
			"place_list": place_list,
			"event_list": event_list,
	}
	return render(request, "profiles/manage.html", __login_proc(request, context))


def syncSuperUser(request):
	superuser_list = User.objects.filter(is_superuser = 1)
	for item in superuser_list:
		pr = Profile(user = item, name=item.username)
		pr.save()
	return HttpResponseRedirect(reverse('index'))


def __login_proc(request, lst):
	if request.user.is_authenticated():
		lst['authenticated'] = True;
		lst['username'] = request.user.username
		return lst
	return lst


def __judge_form(form):
	return True


def __goErrorPage(request, error_list):
	return render(request, "error/error_popup.html", __login_proc(request, {'error_list': error_list}))

ZheNar/templates/profiles/manage.html
{% extends "base.html" %}

{% block css %}
{% endblock %}

{% block script %}
{% endblock %}

{% block main %}
<div class="container" style="padding-top:40px">
	<div class="container-fluid" style="margin-top:40px;padding:0px;">
		<div class="well span4">
			<h2>个人创建地点</h2>
			{% if not place_list %}
			<h4>你还没创建地点哦！</h4>
			{% else %}
				<table class="table">
					<tr>
						<th>地点名</th>
						<th>创建时间</th>
						<th>状态</th>
						<th>管理</th>
					</tr>
					{% for item in place_list %}
					<tr>
						<td>
							<a href="{% url 'places:detail' item.id %}">{{ item.name }}</a>
						</td>
						<td>{{ item.create_time }}</td>
						<td>{{ item.showStatus }}</td>
						<td>
							<a href="{% url 'places:edit' item.id %}">编辑</a>
						</td>
					</tr>
					{% endfor %}
				</table>
			{% endif %}
		</div>
		<div class="well span6">
			<h2>个人创建事件</h2>
			{% if not event_list %}
			<h4>你还没创建事件哦！</h4>
			{% else %}
			<table class="table">
				<tr>
					<th>事件名</th>
					<th>开始时间</th>
					<th>截止时间</th>
					<th>组织</th>
					<th>状态</th>
					<th class="span1">管理</th>
				</tr>
				{% for item in event_list %}
				<tr>
					<td><a href="{% url 'events:detail' item.id %}">{{ item.name }}</a></td>
					<td>{{ item.start_time }}</td>
					<td>{{ item.end_time }}</td>
					<td>{{ item.host_organization }}</td>
					<td>{{ item.showStatus }}</td>
					<td>
						<a class="span1" href="{% url 'events:edit' item.id %}" style="margin-left:0px">编辑</a>
						<a class="span1" href="{% url 'events:_delete' item.id %}" style="margin-left:0px">删除</a>
					</td>
				</tr>
				{% endfor %}
			</table>
			{% endif %}
		</div>
	</div>
</div>

{% endblock %}

ZheNar/templates/profiles/register.html
{% extends "base.html" %}

{% block css %}
{% endblock %}

{% block script %}
<script>

	function checkForm() {
	    return checkUsernameLen() && checkEmailFormat() && checkPasswordFormat() && checkPasswordSame();
	}

	function checkUsernameLen() {
	    var username = document.getElementById("username").value;
	    var len = username.length;
	    if (len < 20 && len > 0) {
	        document.getElementById("username_len").innerHTML="<h5 style='color:green'>OK</h5>";
	        return true;
	    }
	    else if (len == 0) {
	        document.getElementById("username_len").innerHTML="<h5 style='color:red'>不能为空!</h5>";
		return false;
	    }
	    else {
	        document.getElementById("username_len").innerHTML="<h5 style='color:red'>长度必须小于20字符!</h5>";
	        return false;
	    }
	}

	function checkEmailFormat() {
	    var em = document.getElementById("email").value;
	    var reg = /^[\w\-\+\._]+@[\w\-\+\._]+\.[\w\-\+\._]+$/;
	    if (reg.test(em)) {
	        document.getElementById("email_format").innerHTML="<h5 style='color:green'>OK</h5>";
	        return true;
	    }
	    else {
	        document.getElementById("email_format").innerHTML="<h5 style='color:red'>邮件格式不正确!</h5>";
	        return false;
	    }
	}

	function checkPasswordFormat() {
	    var password = document.getElementById("password").value;
	    var len = password.length;
	    var reg = /^[a-zA-Z0-9]+$/;
	    if (reg.test(password)) {
		if (len < 20 && len >= 6) {
	            document.getElementById("password_format").innerHTML="<h5 style='color:green'>OK</h5>";
	            return true;
	    	}
		else {
		    document.getElementById("password_format").innerHTML="<h5 style='color:red'>长度必须在6至20个字符之间!</h5>";
	            return false;
		}
	    }
	    else {
	        document.getElementById("password_format").innerHTML="<h5 style='color:red'>只能使用字母或数字！</h5>";
                return false;
	    }
	}

	function checkPasswordSame() {
	    var pswd_cf = document.getElementById("password_confirm").value;
	    var pswd = document.getElementById("password").value;
	    if ( pswd_cf == pswd ) {
	        document.getElementById("password_same").innerHTML="<h5 style='color:green'>OK</h5>";
	        return true;
	    }
	    else {
	        document.getElementById("password_same").innerHTML="<h5 style='color:red'>两次密码不一致!</h5>";
	        return false;
	    }
	}

</script>

{% endblock %}

{% block main %}
<div class="container" style="padding:40px">
	<div class="span6">
	<div name="register_form" class="span6">
	<form action="{% url 'profiles:_register'  %}" method='post' onsubmit="return checkForm()" >  {% csrf_token %}
		<h2>注册</h2>
		<fieldset>
			<legend>必填信息:</legend>
			<div class="span3">
			  <input type="text" name="username" id="username" style="width:280px;" onChange="checkUsernameLen()" placeholder="用户名" />
			</div>
			<div id="username_len" class="span2" >&nbsp</div>

			<div class="span3">
			  <input type="text" name="email" id="email" style="width:280px;" onChange="checkEmailFormat()" placeholder="电子邮箱Email" />
			</div>
			<div id="email_format" class="span2" >&nbsp</div>

			<div class="span3">
			  <input type="password" name="password" id="password" style="width:280px;" onChange="checkPasswordFormat()" placeholder="密码" />
			</div>
			<div id="password_format" class="span2">&nbsp</div>
			<div class="span3">
			  <input type="password" name="password_confirm" id="password_confirm" style="width:280px;" onChange="checkPasswordSame()" placeholder="确认密码" />
			</div>
			<div id="password_same" class="span2">&nbsp</div>
		</fieldset>
		
		<fieldset>
			<legend>选填信息:</legend>
			<div class="span3">
			  <input type="text" name="name" style="width:280px;" placeholder="真实姓名" />
			</div>
			<div class="span3">
				性别： 男 
				<input type="radio" name="gender" value=1 /> 
				&nbsp 女 
				<input type="radio" name="gender" value=2 />
			</div>
		</fieldset>
	  	<div style='height:30px;'>&nbsp</div>
        	<button class="btn btn-large btn-primary span2" type="submit">注册</button>
	</form>
	</div>
</div>
{% endblock %}

ZheNar/templates/profiles/settings.html
{% extends "base.html" %}

{% block script %}
<script>
	function checkForm() {
		return checkPasswordFormat() && checkPasswordSame();
	}

	function checkPasswordFormat() {
	    if (document.getElementById("change_password0").checked) return true;

	    var password = document.getElementById("password").value;
	    var len = password.length;
	    var reg = /^[a-zA-Z0-9]+$/;
	    if (reg.test(password)) {
		if (len < 20 && len >= 6) {
	            document.getElementById("password_format").innerHTML="<h5 style='color:green'>OK</h5>";
	            return true;
	    	}
		else {
		    document.getElementById("password_format").innerHTML="<h5 style='color:red'>必须在6至20个字符之间!</h5>";
	            return false;
		}
	    }
	    else {
	        document.getElementById("password_format").innerHTML="<h5 style='color:red'>只能使用字母或数字！</h5>";
                return false;
	    }
	}

	function checkPasswordSame() {
	    if (document.getElementById("change_password0").checked) return true;

	    var pswd_cf = document.getElementById("password_confirm").value;
	    var pswd = document.getElementById("password").value;
	    if ( pswd_cf == pswd ) {
	        document.getElementById("password_same").innerHTML="<h5 style='color:green'>OK</h5>";
	        return true;
	    }
	    else {
	        document.getElementById("password_same").innerHTML="<h5 style='color:red'>两次密码不一致!</h5>";
	        return false;
	    }
	}

	function chpswd1() {
		document.getElementById("password_ori").disabled = false;
		document.getElementById("password").disabled = false;
		document.getElementById("password_confirm").disabled = false;
	}
	function chpswd0() {
		document.getElementById("password_ori").disabled = true;
		document.getElementById("password").disabled = true;
		document.getElementById("password_confirm").disabled = true;
	}

</script>
{% endblock %}


{% block main %}
<div class="container" style="padding:40px">
	<div class="span6">
	<div name="register_form" class="span6">
	<form action="{% url 'profiles:_settings'  %}" method='post' onsubmit="return checkForm()" >  {% csrf_token %}
		<h2>个人设置</h2>
		<fieldset>
			<legend>必要信息:</legend>
			<div class="span3">
				<input type="text" name="username" id="username" style="width:280px;" placeholder="用户名" value="{{ pr.user.username }}" disabled/>
			</div>
			<div id="username_len" class="span2" >&nbsp</div>

			<div class="span3">
			  <input type="text" name="email" id="email" style="width:280px;" placeholder="电子邮箱Email" value="{{ pr.user.email }}" disabled />
			</div>
			<div id="email_format" class="span2" >&nbsp</div>

			<div class="span3">
				是否需要修改密码？&nbsp
				是 <input type="radio" name="change_password" id="change_password1" onClick="chpswd1()" value=1 />
				否 <input type="radio" name="change_password" id="change_password0" onClick="chpswd0()" value=0 checked />
			</div>
			<div class="span3">
			  <input type="password" name="password_ori" id="password_ori" style="width:280px;" placeholder="原密码" disabled/>
			</div>
			<div class="span3">
			  <input type="password" name="password" id="password" style="width:280px;" onChange="checkPasswordFormat()" placeholder="密码" disabled/>
			</div>
			<div id="password_format" class="span2">&nbsp</div>
			<div class="span3">
			  <input type="password" name="password_confirm" id="password_confirm" style="width:280px;" onChange="checkPasswordSame()" placeholder="确认密码" disabled/>
			</div>
			<div id="password_same" class="span2">&nbsp</div>
		</fieldset>
		
		<fieldset>
			<legend>选填信息:</legend>
			<div class="span3">
			  <input type="text" name="name" style="width:280px;" placeholder="真实姓名" value="{{ pr.name }}"/>
			</div>
			<div class="span3">
				性别： 男 
				<input type="radio" name="gender" value=1 {{ check1 }}/> 
				&nbsp 女 
				<input type="radio" name="gender" value=2 {{ check2 }}/>
			</div>
		</fieldset>
	  	<div style='height:30px;'>&nbsp</div>
        	<button class="btn btn-large btn-primary span2" type="submit">保存</button>
		<div class="span2">
			{% if back_info != None %}
				<span class="label label-success"><h5>{{ back_info }}</h5></span>
			{% endif %}
		</div>
	</form>
		
	</div>
	<div>
	
</div>
{% endblock %}