ZheNar/ZheNar/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$', 'ZheNar.views.index',name = 'index'),
	url(r'^hot/$','ZheNar.views.hot', name = 'hot'),
	url(r'^admin/', include(admin.site.urls)),
	url(r'^api/', include('api.urls', namespace="api")),
	url(r'^profiles/', include('profiles.urls', namespace="profiles")),
	url(r'^events/', include('events.urls',namespace="events")),
	url(r'^places/', include('places.urls',namespace="places")),
	
	# url(r'^api/', include('api.urls',namespace="api")),
    # Examples:
    # url(r'^$', 'ZheNar.views.home', name='home'),
    # url(r'^ZheNar/', include('ZheNar.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

ZheNar/api/urls.py
from django.conf.urls import patterns, url

from api import views

urlpatterns = patterns('',
	url(r'^$',				views.index, name='index'),
	url(r'^place/$',		views.place, name='place'),
	url(r'^place/type/$',	views.place_type,name='place_type'),
	url(r'^place/create/$', views.place_create,name = 'place_create'),
	url(r'^event/$',		views.event, name='event'),
	url(r'^event/type/$',	views.event_type ,name='event_type'),
	url(r'^event/create/$', views.event_create, name='event_create'),
	url(r'^user/$',			views.user, name='user'),
	url(r'^user/reg/$',		views.user_reg, name='user_reg'),
	url(r'^user/login/username/$',	views.user_login_username, name='user_login_username'),
	url(r'^user/login/email/$',	views.user_login_email, name='user_login_email'),
	url(r'^user/edit/$',		views.user_edit, name='user_edit'),
	url(r'^user/logout/$',		views.user_logout, name='user_logout'),
	url(r'^user/deactive/$',	views.user_deactive, name='user_deactive'),
)

ZheNar/events/urls.py
from django.conf.urls import patterns, url

from events import views

urlpatterns = patterns('',
	url(r'^$',views.index,name='index'),
	url(r'^create/$',views.create,name='create'),
	url(r'^_create/$',views._create,name='_create'),
	url(r'^type_create/$',views.type_create,name='type_create'),
	url(r'^_type_create/$',views._type_create,name='_type_create'),
	url(r'^detail/(?P<event_id>\d+)/$',views.detail,name='detail'),
	url(r'^_follow/$',views._follow,name='_follow'),
	url(r'^_unfollow/$',views._unfollow,name='_unfollow'),
	url(r'^insert/$',views.insert,name="insert"), #insert the icon
	url(r'^_delete/(?P<e_id>\d+)/$', views._delete,name='_delete'),
	url(r'^edit/(?P<event_id>\d+)/$',views.edit,name='edit'),
	url(r'^_edit/(?P<event_id>\d+)/$',views._edit,name='_edit'),
)

ZheNar/events/models.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django.db import models
from profiles.models import Profile
from django.contrib.auth.models import User
from django.utils import timezone

from places.models import Place

class Icon(models.Model):
	name = models.CharField(unique=True,max_length=255)
	
	def __unicode__(self):
		return self.name[:-4]

# Create your models here.
class EventType(models.Model):
	#name = models.CharField(max_length = 255)
	STATUS_SET = (
	(1,_("Pending")),
	(2,_("Accepted")),
	(3,_("Rejected")),
	(4,_("Deleted")),
	)
	status = models.SmallIntegerField(default = 1,choices = STATUS_SET)
	name = models.CharField(max_length = 255,blank=False)
	icon = models.ForeignKey(Icon)

	def __unicode__(self):
		return self.name


class Event(models.Model):
	CHOICE_SET = (
	(1,_("Pending")),
	(2,_("Accepted")),
	(3,_("Rejected")),
	(4,_("Deleted")),
	)
	
	status = models.SmallIntegerField(default = 1,choices = CHOICE_SET)
	name = models.CharField(max_length = 255)
	description = models.TextField(blank = True)
	holder = models.ForeignKey(Profile, related_name='event_holder_set')#
	host_organization = models.CharField(max_length = 255, null = True)
	start_time = models.DateTimeField('Time that activities started')
	end_time = models.DateTimeField('Time that activities ended')
	place = models.ForeignKey(Place, related_name='place_events_set')
	event_type = models.ForeignKey(EventType)
	follower = models.ManyToManyField(Profile, related_name='event_follower_set', null = True)
	address = models.CharField(max_length = 255,default = 'Not mentioned')
	pic_name = models.CharField(max_length = 255, default = 'event_default.png')
	
	def __unicode__(self):
		return self.name
	
	def follower_count(self):
		return self.follower.count()
	
	def if_event_was_expired(self):
		return self.end_time < timezone.now()

	def showStatus(self):
		if self.status == 1: return "Pending"
		if self.status == 2: return "Accepted"
		if self.status == 3: return "Rejected"

	if_event_was_expired.boolean = True
	if_event_was_expired.short_description = "Expired?"
	
	class Meta:
		ordering = ['name']
		permissions = (
			('create_map_event', 'Can create map event'),
			('modify_map_event', 'Can modify map event'),
			('remove_map_event', 'Can remove map event'),
		)

ZheNar/events/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render_to_response, render
from django.template import Context, loader, RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db.models import Count
from django.views.decorators.http import require_POST, require_GET

from datetime import datetime
from profiles.models import Profile
import time
import json

from events.models import Event, EventType, Icon
from places.models import Place

def login_proc(request):
	if request.user.is_authenticated():
		return {
			"authenticated":True, 
			"username":request.user,
			}
	else:
		return {}


def index(request):
	event_list_query = Event.objects.filter(status=2)
	event_list = [event for event in event_list_query if not event.if_event_was_expired()]
	pr = Profile.objects.get(user_id = request.user.id)
	followed_event = pr.event_follower_set.filter(status=2)
	"""
	for event in event_list:
		follower_list = event.follower.all()
		for man in follower_list:
			if man == user:
				followed_event.append(event)
	"""
	c = {
			'page_title': "浙Nar儿的事件",
			'event_list': event_list,
			'followed_event_list': followed_event,
	}
	return render_to_response("events/event_index.html",c,context_instance = RequestContext(request,processors=[login_proc]))

def _follow(request):
	event_id = request.POST.get("clicked_id")
	m_event = Event.objects.get(pk = event_id)

	m_event.follower.add(Profile.objects.get(user_id = request.user.id))
	return HttpResponse(json.dumps({"status":"succeed", }))

def _unfollow(request):
	event_id = request.POST.get("clicked_id")
	m_event = Event.objects.get(pk = event_id)
	
	m_event.follower.remove(Profile.objects.get(user_id = request.user.id))
	return HttpResponse(json.dumps({"status":"succeed", }))

def detail(request,event_id):
	try:
		m_event = Event.objects.get(pk = event_id)
	except Event.DoesNotExist:
		return __goErrorPage(request, ['There is no such event', ])
	m_follower = m_event.follower.all()[0:5]
	 
	c = Context({"page_title": "浙Nar儿的事件详情",
	"event": m_event,
	"followers": m_follower,
	})
	return render_to_response('events/event_detail.html',c,context_instance = RequestContext(request,processors=[login_proc]))

def create(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse("index"))
	place_list = Place.objects.filter(status = 2)
	event_type_list = EventType.objects.filter(status = 2)
	c = {
			'page_title': "创建事件喽",
			'place_list': place_list,
			'event_type_list': event_type_list,
	}
	return render_to_response("events/event_create.html",c,context_instance = RequestContext(request,processors=[login_proc]))
	

def _create(request):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse("index"))
	name = request.POST.get("name")
	description = request.POST.get("description")
	holder = Profile.objects.get(user_id = request.user.id)
	host_organization = request.POST.get("host_organization")
	start_time_string = request.POST.get("start_time")
	start_time = datetime.strptime(start_time_string,"%m/%d/%Y %H:%M:%S")
	end_time_string = request.POST.get("end_time")
	end_time = datetime.strptime(end_time_string,"%m/%d/%Y %H:%M:%S")
	place_id = request.POST.get("place_id")
	event_type_id = request.POST.get("event_type_id")
	address = request.POST.get("address")
	
	try:
		obj_place = Place.objects.get(pk=place_id, status = 2)
	except Place.DoesNotExist:
		return __goErrorPage(request, ['There is no such place', ])
	try:
		obj_place = EventType.objects.get(pk=event_type_id, status = 2)
	except EventType.DoesNotExist:
		return __goErrorPage(request, ['There is no such event type', ])
	
	form = {}
	if __judge_form(form):
		event = Event(name=name, description=description, holder=holder, host_organization=host_organization, start_time=start_time, end_time=end_time, place_id=place_id, event_type_id=event_type_id, address = address)
		event_pic = request.FILES.get('event_pic')
		if request.user.is_superuser: 
			event.status = 2
		event.save()
		if event_pic is not None:
			event.pic_name = handle_uploaded_pic(event_pic, event.id)
			event.save()
		
	else:
		return __goErrorPage(request, ['Something wrong with your form', ])

	return HttpResponseRedirect(reverse("events:index"))


def handle_uploaded_pic(f, _id):
    pic_name = "event_" + str(_id) + ".jpg"
    with open('static/image/event_pic/' + pic_name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)
    return pic_name


def type_create(request):
	if request.user.is_authenticated():
		type_icon_list = Icon.objects.all()
		c = {
				'page_title': "浙哪儿事件类型创建", 
				'icon_list': type_icon_list,
		}
		return render_to_response("events/event_type_create.html",c,context_instance = RequestContext(request,processors=[login_proc]))
	else :
		return HttpResponseRedirect(reverse('places:index'))


@require_POST
def _type_create(request):
	error_list = []
	if request.POST:
		m_type_name = request.POST.get("event_type")
		m_type_icon = request.POST.get("event_icon")
	else:
		return HttpResponseRedirect(reverse('events:index'))
		
	try:
		m_type = EventType.objects.get(name = m_type_name,status = 2)
	except EventType.DoesNotExist:
		m_icon = Icon.objects.get(name = m_type_icon)
		m_type = EventType(name = m_type_name, icon = m_icon)
		if request.user.is_superuser: 
			m_type.status = 2
		m_type.save()
		return HttpResponseRedirect(reverse('events:index'))
	
	return HttpResponseRedirect(reverse('index'))


def _delete(request, e_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse('index'))
	event = Event.objects.get(pk = e_id)
	pr = Profile.objects.get(user_id = request.user.id)
	if event.holder_id == pr.id:
		event.status = 4
		event.save()
	return HttpResponseRedirect(reverse('profiles:manage'))


def edit(request, event_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse("index"))
	event = Event.objects.get(pk=event_id)
	pr = Profile.objects.get(user_id = request.user.id)
	if event.holder_id != pr.id:
		return HttpResponseRedirect(reverse("index"))

	place_list = Place.objects.filter(status = 2)
	event_type_list = EventType.objects.filter(status = 2)
	context = {
			'page_title': "创建事件喽",
			'place_list': place_list,
			'event_type_list': event_type_list,
			'event':event,
			'event_start_time': event.start_time.strftime("%m/%d/%Y %H:%M:%S"),
			'event_end_time': event.end_time.strftime("%m/%d/%Y %H:%M:%S"),
	}
	return render(request, "events/event_edit.html", __login_proc(request, context))

def _edit(request, event_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect(reverse("index"))
	event = Event.objects.get(pk=event_id)
	pr = Profile.objects.get(user_id = request.user.id)
	if event.holder_id != pr.id:
		return HttpResponseRedirect(reverse("index"))

	name = request.POST.get("name")
	description = request.POST.get("description")
	holder = Profile.objects.get(user_id = request.user.id)
	host_organization = request.POST.get("host_organization")
	start_time_string = request.POST.get("start_time")
	start_time = datetime.strptime(start_time_string,"%m/%d/%Y %H:%M:%S")
	end_time_string = request.POST.get("end_time")
	end_time = datetime.strptime(end_time_string,"%m/%d/%Y %H:%M:%S")
	place_id = request.POST.get("place_id")
	event_type_id = request.POST.get("event_type_id")
	address = request.POST.get("address")
	
	try:
		obj_place = Place.objects.get(pk=place_id, status = 2)
	except Place.DoesNotExist:
		return __goErrorPage(request, ['There is no such place', ])
	try:
		obj_place = EventType.objects.get(pk=event_type_id, status = 2)
	except EventType.DoesNotExist:
		return __goErrorPage(request, ['There is no such event type', ])
	
	form = {}
	if __judge_form(form):
		event.name = name
		event.description=description
		event.holder=holder
		event.host_organization=host_organization
		event.start_time=start_time
		event.end_time = end_time
		m_place = Place.objects.get(pk = place_id)
		event.place = m_place
		m_event_type = EventType.objects.get(pk = event_type_id)
		event.event_type = m_event_type
		event.address = address
		if request.user.is_superuser: 
			event.status = 2
		event_pic = request.FILES.get('event_pic')
		if event_pic is not None:
			event.pic_name = handle_uploaded_pic(event_pic, event.id)
		event.save()
	else:
		return __goErrorPage(request, ['Something wrong with your form', ])

	return HttpResponseRedirect(reverse("events:index"))


def __judge_form(form):
	return True


def __goErrorPage(request, error_list):
	return render(request, "error/error_popup.html", __login_proc(request, {'error_list': error_list}))


def __login_proc(request, lst):
	if request.user.is_authenticated():
		lst['authenticated'] = True;
		lst['username'] = request.user.username
		return lst
	return lst
	

# 用于插入icon&place_type用，已插入则无需再用
def insert(request):
	list = []
	f = open('static/map_icon/icons/icon_list.txt','r')
	for line in f:
		list += line.splitlines()
	for item in list:
		icon = Icon(name= item)
		icon.save()
	

	return HttpResponseRedirect(reverse('events:index'))

ZheNar/templates/events/event_detail.html
{% extends "base.html" %}
{% block css %}
<style>
.description{
	position: relative;
	margin: 0px 0px 20px 0px;
	padding: 10px 20px 10px 20px;
	background-color: #fff;
	border: 1px solid #ddd;
	-webkit-border-radius: 4px;
	-moz-border-radius: 4px;
	border-radius: 4px;
	height:300px;
	overflow:scroll;
}
#follower-list{
	height:300px;
	overflow: scroll;
}
</style>
{% endblock %}
{% block script %}
<script>
	function Setup_follow_button(){
		{% for man in followers %}
		{% if man.user_id == username.id %}
			$("#follow").hide();
			$("#unfollow").show();
		{% endif %}
		{% endfor %}
	}

	$(document).ready(function()
	{
		Setup_follow_button();
		function getCookie(name) {
			var cookieValue = null;
			if (document.cookie && document.cookie != '') {
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = jQuery.trim(cookies[i]);
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) == (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');
		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$.ajaxSetup({
			crossDomain: false, // obviates need for sameOrigin test
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type)) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});
		$("#follow").click(function()
		{
			m_event_id = {{event.id}}
			$("#follow").hide();
			$("#unfollow").show();
			$("#follower-table").append( "<tr id='follower"+"{{username.id}}"+"'><td><span class='label label-info'>关注者</span></td><td>{{username}}</td></tr>");

			$("#counter").text(parseInt($("#counter").text())+1);
			$.ajax({
				url:"{% url 'events:_follow'%}",
				type:"POST",
				data:{ clicked_id:m_event_id},
			})
		});
		$("#unfollow").click(function(){
			m_event_id = {{event.id}};
			$("#follow").show();
			$("#unfollow").hide();
			$("#counter").text(parseInt($("#counter").text())-1);
			$("#follower-table").find("#follower{{username.id}}").remove();
			$.ajax({
				url:"{% url 'events:_unfollow'%}",
				type:"POST",
				data:{ clicked_id:m_event_id},
			})
		});
	});
</script>

{% endblock %}
{% block main %}
<div class="container" style="padding:40px;">
	<div class="row-fluid" style="margin-top:40px;">
		<div class="span4">
			<div class="thumbnail">
				<img src="/static/image/event_pic/{{event.pic_name}}" style="width:348px;max-height:400px;">
				<div class="caption">
					{% if authenticated %}
					<div class="pull-right">
						<a id="follow" class="btn btn-info btn-small" style="margin:10px 0 10px 0; padding:5px 5px 2px 5px;">
							<strong class="follow-star">关注</strong>
						</a>
						<a id="unfollow" class="btn btn-info btn-small" style="margin:10px 0 10px 0;padding:5px 5px 2px 5px;display:none;">
							<strong class="unfollow-star">取消</strong>
						</a>
					</div>
					{% endif %}
					<h3 calss="pull-left">{{event.name}}<span class="badge badge-info" style="margin-bottom:5px;">{{ event.event_type.name}}</span></h3>
					<table class="table table-hover">
						<tr>
							<td>创建人:</td>
							<td>{{event.holder.name}}</td>
						</tr>
						<tr>
							<td>举办组织:</td>
							<td>{{event.host_organization}}</td>
						</tr>
						<tr>
							<td>开始时间:</td>
							<td>{{event.start_time}}</td>
						</tr>
						<tr>
							<td>结束时间:</td>
							<td>{{event.end_time}}</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
		<div class="span7" style="margin-left:60px">
			<div class="row media">
				<div class="description">
					<p>
						<div class="label">事件描述</div>
						{{event.description}}
					</p>
				</div>
			</div>
			<div class="row media well">
				<a class="pull-left" href="#">
					<img class="media-object" src="http://maps.googleapis.com/maps/api/staticmap?center={{event.place.latitude}},{{event.place.longitude}}&zoom=16&size=200x200&sensor=false&markers=icon:http://google-maps-icons.googlecode.com/files/{{event.place.place_type.icon.name}}%7Clabel:Z%7C{{event.place.latitude}},{{event.place.longitude}}">
				</a>
				<div class="media-body">
					<table class="table table-hover">
						<caption>
							<h4>事件地点信息</h4>
						</caption>
						<tr>
							<td>举办地点</td>
							<td>
								<strong><a href="{% url 'places:detail' event.place.id %}">{{ event.place.name}}</a></strong>
								<span class="badge badge-info">{{ event.place.place_type.name}}</span>
							</td>
						</tr>
						<tr>
							<td>具体地点</td>
							<td>{{event.address}}</td>
						</tr>
						<tr>
							<td colspan="2"><p style="height:80px;overflow:scroll;">{{event.place.description}}</p></td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row-fluid" style="margin-top:10px;">
		<div class="span4">
			<div id="follower-list" class="well">
				<table id="follower-table" class="table table-striped" cellspacing="5" cellpadding="5">
					<caption><h4>事件关注度</h4></caption>
					<tr>
						<th><span class="label label-info">热度</span></th>
						<th id="counter" class="span3">{{event.follower_count}}</th></tr>
					{% for man in followers %}
						
					<tr id="follower{{man.user_id}}"><td><span class="label label-info">关注者</span></td><td>{{ man.user.username }}</td></tr>
						
					{% endfor %}
				</table>
			</div>
		</div>
		<div class="forum span7">
			
		</div>
	</div>
</div>
{% endblock %}

ZheNar/templates/events/event_hot.html
{% extends "base.html" %}
{% block css %}
<style>
img.media-object{
	height:100px;
	width:100px;
}
.image-list{
	margin-top: 15px;
}
.follow-star{
	display: inline-block;
	font-size: 16px;
	position: relative;
	width: 1.1em;
}
.unfollow-star{
	display: inline-block;
	font-size: 16px;
	position: relative;
	width: 1.1em;
}
.ranking{
	font-size: 24px;
}
.media{
	margin-top: 0px;
}
</style>
{% endblock %}

{% block script %}
<script>
	function Setup_follow_button(){
		{% for event in followed_event_list %}
			$("#follow{{event.id}}").hide();
			$("#unfollow{{event.id}}").show();
		{% endfor %}
	}
	
	$(document).ready(function()
	{
		Setup_follow_button();
		function getCookie(name) {
			var cookieValue = null;
			if (document.cookie && document.cookie != '') {
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = jQuery.trim(cookies[i]);
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) == (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		var csrftoken = getCookie('csrftoken');
		function csrfSafeMethod(method) {
			// these HTTP methods do not require CSRF protection
			return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
		}
		$.ajaxSetup({
			crossDomain: false, // obviates need for sameOrigin test
			beforeSend: function(xhr, settings) {
				if (!csrfSafeMethod(settings.type)) {
					xhr.setRequestHeader("X-CSRFToken", csrftoken);
				}
			}
		});
		$(".follow").click(function()
		{
			m_event_id = $(this).attr("name");
			$("#follow"+m_event_id).hide();
			$("#unfollow"+m_event_id).show();
			
			$("span#counter"+m_event_id).text(parseInt($("span#counter"+m_event_id).text())+1);
			$.ajax({
				url:"{% url 'events:_follow'%}",
				type:"POST",
				data:{ clicked_id:m_event_id},
			})
		});
		$(".unfollow").click(function(){
			m_event_id = $(this).attr("name");
			$("#follow"+m_event_id).show();
			$("#unfollow"+m_event_id).hide();
			$("span#counter"+m_event_id).text(parseInt($("span#counter"+m_event_id).text())-1);
			$.ajax({
				url:"{% url 'events:_unfollow'%}",
				type:"POST",
				data:{ clicked_id:m_event_id},
			})
		});
		$(".unfollow").mouseover(function(){
			m_id = $(this).attr("name");
			if(!$("#unfollow_icon"+m_id).hasClass("icon-spin"))
				$("#unfollow_icon"+m_id).addClass("icon-spin");
		});
		$(".unfollow").mouseout(function(){
			m_id = $(this).attr("name");
			if($("#unfollow_icon"+m_id).hasClass("icon-spin"))
				$("#unfollow_icon"+m_id).removeClass("icon-spin");
		})
	});
</script>
{% endblock %}
{% block main %}
<div class="container" style="padding:50px">
	<div class="container-fluid" style="margin-top:40px">
		<div class="span3 well">
			<h1>Top 10 Places</h1>
		</div>
	 	<div class="span7 well">
			<h1>Top 10 Events</h1>
			{% for event in hot_event_list %}
			<div class="media" >
				<div class="media-body">
					<div class="image-list pull-left">
						<strong class="ranking">No.{{forloop.counter}}</strong>
						<img src="/static/map_icon/numeric/redhot.png">
						<img src="/static/map_icon/icons/{{event.event_type.icon.name}}">
						<img src="/static/map_icon/icons/{{event.place.place_type.icon.name}}">
					</div>
					<div class="media pull-right">
						<a id="info{{event.id}}" name="{{event.id}}" class="btn btn-info btn-small" style="margin:10px 0 10px 0;" href="{% url 'events:detail' event.id %}">更多信息</a>
						<a id="follow{{event.id}}" name="{{event.id}}" class="btn btn-info btn-small follow" style="margin:10px 0 10px 0; padding:5px 5px 2px 5px;">
							<strong class="follow-star">☆</strong>
						</a>
						<a id="unfollow{{event.id}}" name="{{event.id}}" class="btn btn-info btn-small unfollow" style="margin:10px 0 10px 0;padding:5px 5px 2px 5px;display:none;">
							<strong class="unfollow-star">★</strong>
						</a>
					</div>
					<table class="table">
						<tr style="height:">
							<td><h4 class="media-heading">{{event.name}}</h4></td>
							<td><h5 class="media-heading">开始时间:</h5>{{event.start_time}}</td>
							<td><h5 class="media-heading">结束时间:</h5>{{event.end_time}}</td>
							<td><h5 class="media-heading">地点:</h5>{{event.place}}</td>
							<td class="span1">
								<div class="span1" style="margin-left:0px;">
									<span><strong>关注度</strong></span>
									<span id="counter{{event.id}}" class="label label-info">{{event.follower_count}}</span>
								</div>
							</td>
						</tr>
					</table>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}